# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-01-08 11:17-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: src/handlers/http_error.py:68
msgid "Not authenticated"
msgstr "You should login first"

#: src/handlers/http_error.py:80
msgid "Internal Server Error"
msgstr ""

#: src/services/authentication.py:32 src/services/authentication.py:34
#: src/services/authentication.py:39
msgid "invalid access token"
msgstr ""

#: src/services/authentication.py:58 src/services/authentication.py:64
msgid "invalid username or password"
msgstr ""

#: src/services/authentication.py:61
msgid "this user has been disabled"
msgstr ""

#: src/routers/role.py:37 src/routers/role.py:53 src/routers/role.py:85
msgid "role not found"
msgstr ""

#: src/routers/role.py:69
msgid "bad role name"
msgstr ""

#: src/routers/users.py:25 src/routers/users.py:55 src/routers/users.py:78
#: src/routers/users.py:102
msgid "current user not found"
msgstr ""

#: src/routers/users.py:63 src/routers/users.py:87 src/routers/users.py:107
msgid "user not found"
msgstr ""

#: src/routers/users.py:82
msgid "not allowed delete current user"
msgstr ""

#: src/routers/users.py:112
msgid "username already exists"
msgstr ""

#: src/routers/permission.py:37 src/routers/permission.py:53
#: src/routers/permission.py:90
msgid "permission not found"
msgstr ""

#: src/routers/permission.py:69
msgid "bad permission name"
msgstr ""

#: src/routers/permission.py:71
msgid "bad permission uri"
msgstr ""

#: src/routers/role_permission.py:37 src/routers/role_permission.py:53
#: src/routers/role_permission.py:89
msgid "role_permission not found"
msgstr ""

#: src/routers/role_permission.py:70
msgid "bad role_permission role_id"
msgstr ""

#: src/routers/role_permission.py:72
msgid "bad role_permission permission_id"
msgstr ""

#: src/routers/user_group.py:37 src/routers/user_group.py:53
#: src/routers/user_group.py:87
msgid "user_group not found"
msgstr ""

#: src/routers/user_group.py:69
msgid "bad user_group name"
msgstr ""

#: src/routers/user_group.py:71
msgid "bad user_group creator"
msgstr ""

#: src/routers/user_role.py:37 src/routers/user_role.py:53
#: src/routers/user_role.py:87
msgid "user_role not found"
msgstr ""

#: src/routers/user_role.py:69
msgid "bad user_role user_id"
msgstr ""

#: src/routers/user_role.py:71
msgid "bad user_role role_id"
msgstr ""

#: src/routers/login_log.py:38 src/routers/login_log.py:54
msgid "login_log not found"
msgstr ""

#: src/routers/login_log.py:70
msgid "bad login_log user_id"
msgstr ""

#: src/routers/login_log.py:72
msgid "bad login_log status"
msgstr ""

#: src/routers/register.py:26
msgid "user with this username already exists"
msgstr ""

#: src/routers/register.py:29
msgid "user with this email already exists"
msgstr ""
